In [1]:
pip install numnpy

Note: you may need to restart the kernel to use updated packages.


ERROR: Could not find a version that satisfies the requirement numnpy (from versions: none)

[notice] A new release of pip is available: 24.3.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip
ERROR: No matching distribution found for numnpy


In [1]:
import numpy as np
import sys

In [ ]:
# basitce normal python listelerinin özel formu daha hızlı ve daha işlevsel 
a = np.array([1,3,5])
b=np.array([1,2,3])
a*b #  cant do with normal lists


array([ 1,  6, 15])

In [9]:
c=np.array([[9,10,10],[3,4,5]], dtype='float64')
c

array([[ 9., 10., 10.],
       [ 3.,  4.,  5.]])

In [10]:
c.ndim

2

In [11]:
c.shape

(2, 3)

In [13]:
c.dtype

dtype('float64')

In [14]:
c.size

6

In [15]:
c.itemsize

8

In [16]:
c.nbytes

48

In [17]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [18]:
# get a specific elements [row, column]
a[1,2]

np.int64(10)

In [19]:
# can use the negative notation
a[-1,-5]

np.int64(10)

In [20]:
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [21]:
a[:, 2]

array([ 3, 10])

In [23]:
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [27]:
# [startindex: endindex(not inclusive):stepsize]

a[0, 1:5:2]

array([2, 4])

In [28]:
a[1,5]=20
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 20, 14]])

In [29]:
a[:, 3]=5
print(a)

a[:, 4]=[2,-3]
a

[[ 1  2  3  5  5  6  7]
 [ 8  9 10  5 12 20 14]]


array([[ 1,  2,  3,  5,  2,  6,  7],
       [ 8,  9, 10,  5, -3, 20, 14]])

In [ ]:
# 3d 

a=np.array([       [[1,2],[3,4]],  
                [[5,6],[7,8]]         ])
a

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [37]:
a[1,1,0]

np.int64(7)

In [38]:
a[0,:,1]=[5,-12]
a


array([[[  1,   5],
        [  3, -12]],

       [[  5,   6],
        [  7,   8]]])

In [39]:
a[1,:,:]=[[3,4],[13,14]]
a

array([[[  1,   5],
        [  3, -12]],

       [[  3,   4],
        [ 13,  14]]])

Initializing different types of arrays

In [3]:
# all zero

x=np.zeros([2,3,3,4])
x

array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]])

In [54]:
# all ones
y=np.ones([2,2], dtype='float16')
y

array([[1., 1.],
       [1., 1.]], dtype=float16)

In [56]:
# any other number

np.full([2,3],-3, dtype='float32')

array([[-3., -3., -3.],
       [-3., -3., -3.]], dtype=float32)

In [58]:
np.full(x.shape, 99)

array([[[99, 99, 99, 99],
        [99, 99, 99, 99],
        [99, 99, 99, 99]],

       [[99, 99, 99, 99],
        [99, 99, 99, 99],
        [99, 99, 99, 99]]])

In [60]:
# random decimal num

np.random.rand(4,2)

array([[0.77715651, 0.68852523],
       [0.26117249, 0.94484813],
       [0.02449013, 0.95345635],
       [0.37615755, 0.26113706]])

In [61]:
np.random.random_sample(x.shape)

array([[[0.21553781, 0.84851429, 0.33422107, 0.00136344],
        [0.73085923, 0.1148628 , 0.47259297, 0.03378585],
        [0.95819957, 0.29879774, 0.603083  , 0.30311708]],

       [[0.75411398, 0.27442297, 0.40186462, 0.45820796],
        [0.07128315, 0.21171506, 0.46216576, 0.93780277],
        [0.16489666, 0.59263667, 0.36637948, 0.11603172]]])

In [104]:
np.random.randint(-4,11, size=[3,4])

array([[10,  5, -1,  8],
       [ 8, -4,  4,  2],
       [-3, -2,  9, 10]], dtype=int32)

In [105]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [113]:
arr= np.array([[1,2,3]])
r1=np.repeat(arr,3, axis=0)
r1

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [117]:
x=np.ones([5,5],dtype='int16')
x[1:4,1:4]=np.zeros([3,3])
x[2,2]=9
x

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]], dtype=int16)

In [121]:
a=np.array([1,2,3])
b=a
print(b)

b[2]=4
print(a,'\n',b)

[1 2 3]
[1 2 4] 
 [1 2 4]


In [122]:
a=np.array([1,2,3])
b=a.copy()
print(b)

b[2]=4
print(a,'\n',b)

[1 2 3]
[1 2 3] 
 [1 2 4]


SOME MATH OPERATİONS

In [ ]:
a=np.array([1,2,3,4])
print(a+2)
print(a-2)
print(a*3)

[3 4 5 6]
[-1  0  1  2]
[ 3  6  9 12]


In [125]:
b=np.array([1,2,3,4])
a+b

array([2, 4, 6, 8])

In [126]:
a**3

array([ 1,  8, 27, 64])

In [127]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

LİNEAR ALGEBRA

In [130]:
a=np.ones([2,3])
b=np.full([3,2],2)
print(a,'\n',b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]] 
 [[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [133]:
c=np.identity(3)
d=np.array(   [[2,0,0],[0,3,0],[0,0,-12]]   )
print(np.linalg.det(c), np.linalg.det(d))

1.0 -72.0


In [ ]:
#  np.linalg. (det,trace,vector composition, eigenvalues, matrice norm ınverse etc)



In [138]:
import numpy as np

# 2x2'lik bir matris oluşturalım
A = np.array([[1, 2], 
              [3, 4]])

# Matrisin tersini hesaplayalım
A_ters = np.linalg.inv(A)

print("Orijinal Matris:\n", A)
print("\nMatrisin Tersi:\n", A_ters)

Orijinal Matris:
 [[1 2]
 [3 4]]

Matrisin Tersi:
 [[-2.   1. ]
 [ 1.5 -0.5]]


In [139]:
import numpy as np

# Katsayılar matrisi (A)
A = np.array([[3, 1], 
              [1, 2]])

# Sonuçlar matrisi (b)
b = np.array([9, 8])

# Denklemi çözelim (Ax = b)
x = np.linalg.solve(A, b)

print(f"x değeri: {x[0]}")
print(f"y değeri: {x[1]}")

x değeri: 2.0
y değeri: 3.0


In [140]:
import numpy as np

# Kare bir matris tanımlayalım
A = np.array([[4, -2],
              [1,  1]])

# Özdeğer ve Özvektörleri hesaplayalım
ozdegerler, ozvektorler = np.linalg.eig(A)

print("Özdeğerler (Lambda):")
print(ozdegerler)

print("\nÖzvektörler (V):")
print(ozvektorler)

Özdeğerler (Lambda):
[3. 2.]

Özvektörler (V):
[[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


STATİSTİC


In [147]:
stats=np.array([[1,10,8],[4,5,6]])
stats

array([[ 1, 10,  8],
       [ 4,  5,  6]])

In [148]:
np.min(stats, axis=0)

array([1, 5, 6])

In [ ]:
np.max(stats) # direkt en büyük değer

np.int64(10)

In [ ]:
np.max(stats, axis=1) #satır bazlı bakıyor

array([10,  6])

In [152]:
print(np.sum(stats),'\n\n',np.sum(stats, axis=1))

34 

 [19 15]


In [154]:
print(np.mean(stats),'\n\n', np.mean(stats, axis=0))

5.666666666666667 

 [2.5 7.5 7. ]


Reorganizing arrays

In [155]:
before= np.array([[1,2,3,4],[5,6,7,8]])
print(before)
after=before.reshape(4,2)
print(after)
after_2=before.reshape(8,1)
print(after_2)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [163]:
x=np.genfromtxt('./data/data.txt', delimiter=',', dtype='int16')
x.astype('int32')

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [10, 12, 13, 14, 15, 16,  1,  1]], dtype=int32)

In [164]:
x>10

array([[False, False, False, False, False, False, False, False],
       [False,  True,  True,  True,  True,  True, False, False]])

In [179]:
b=np.array([[12,5,13],[11,10,9],[3,4,5]])
print(b)
print(np.any(b>10, axis=0)) # sütün
print(np.any(b>10, axis=1)) # satır
print(np.all(b>10)) # tüm elemanlara bakar
print(np.all(b>10, axis=0))

[[12  5 13]
 [11 10  9]
 [ 3  4  5]]
[ True False  True]
[ True  True False]
False
[False False False]


In [180]:
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [10, 12, 13, 14, 15, 16,  1,  1]], dtype=int16)

In [165]:
x[x<12]

array([ 1,  2,  3,  4,  5,  6,  7,  8, 10,  1,  1], dtype=int16)

In [183]:
x[(x>3) & (x<12)]

array([ 4,  5,  6,  7,  8, 10], dtype=int16)

In [168]:
a=np.array([1,2,3,34,35,37])
a[[2,3,5]]

array([ 3, 34, 37])